package it.ded.pg.model.prova.capacita.inizializzazioneCapacita;

import it.ded.pg.model.prova.capacita.MagieMagoEStregone;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;
@Data
public class InizializzazioneMagieMagoEStregone {

    private List<MagieMagoEStregone> lvl0 = new ArrayList<>();
    private List<MagieMagoEStregone> lvl1 = new ArrayList<>();
    private List<MagieMagoEStregone> lvl2 = new ArrayList<>();
    private List<MagieMagoEStregone> lvl3 = new ArrayList<>();
    private List<MagieMagoEStregone> lvl4 = new ArrayList<>();
    private List<MagieMagoEStregone> lvl5 = new ArrayList<>();
    private List<MagieMagoEStregone> lvl6 = new ArrayList<>();
    private List<MagieMagoEStregone> lvl7 = new ArrayList<>();
    private List<MagieMagoEStregone> lvl8 = new ArrayList<>();
    private List<MagieMagoEStregone> lvl9 = new ArrayList<>();


    public void InizializzazioneMagie() {

        lvl0.add(new MagieMagoEStregone("Abiurazione", "Resistenza", "Il soggetto ottiene bonus di +1 ai tiri salvezza"));
        lvl0.add(new MagieMagoEStregone("Ammaliamento", "Frastornare", "Una creatura umanoide con 4 DV o meno perde l'azione successiva"));
        lvl0.add(new MagieMagoEStregone("Divinazione", "Individuazione del magico", "Individua incantesimi e oggetti magici nel raggio di 18 m"));
        lvl0.add(new MagieMagoEStregone("Divinazione", "Individuazione del veleno", "Individua il veleno in una creatura o in tin oggetto"));
        lvl0.add(new MagieMagoEStregone("Divinazione", "Lettura del magico", "Per leggere pergamene e libri degli incantesimi"));
        lvl0.add(new MagieMagoEStregone("Evocazione", "Fiotto acido", "Sfera che infligge 1d3 danni da acido"));
        lvl0.add(new MagieMagoEStregone("Illusione", "Suono fantasma", "Suoni illusori"));
        lvl0.add(new MagieMagoEStregone("Invocazione", "Lampo", "Abbaglia una creatura (-1 ai tiri per colpire)"));
        lvl0.add(new MagieMagoEStregone("Invocazione", "Luce", "toggetto risplende come una torcia"));
        lvl0.add(new MagieMagoEStregone("Invocazione", "Luci danzanti", "Crea torce illusorie o altre luci"));
        lvl0.add(new MagieMagoEStregone("Invocazione", "Raggio di gelo", "Raggio che infligge 1d3 danni da freddo"));
        lvl0.add(new MagieMagoEStregone("Necromanzia", "Distruggere non morti", "Infligge 1d6 danni a un non morto"));
        lvl0.add(new MagieMagoEStregone("Necromanzia", "II Tocco di affaticamento", "Attacco di contatto rende affaticato il bersaglio"));
        lvl0.add(new MagieMagoEStregone("Trasmutazione", "Aprire/Chiudere", "Apre o chiude oggettipiccoli o leggeri"));
        lvl0.add(new MagieMagoEStregone("Trasmutazione", "Mano magica", "Telecinesi per 2,5 kg"));
        lvl0.add(new MagieMagoEStregone("Trasmutazione", "Messaggio", "Conversazione sussurrata a distanza"));
        lvl0.add(new MagieMagoEStregone("Trasmutazione", "Riparare", "Effettua riparazioni minori su un oggetto"));
        lvl0.add(new MagieMagoEStregone("Universale", "Prestidigitazione", "Effettua trucchi minori"));
        lvl0.add(new MagieMagoEStregone("Universale", "Sigillo arcano", "Trascrive una ima personale (visibile o invisibile)"));


        lvl1.add(new MagieMagoEStregone("Abiurazione", "Allarme", "Sorveglia un'area per 2 ore per livello"));
        lvl1.add(new MagieMagoEStregone("Abiurazione", "Blocca porte", "Tiene una porta chiusa"));
        lvl1.add(new MagieMagoEStregone("Abiurazione", "Contrastare elementi", "A proprio agio in un ambiente freddo o caldo"));
        lvl1.add(new MagieMagoEStregone("Abiurazione", "Protezione dal bene/caos/legge/male", "+2 alla CA e ai tiri salvezza ; contrasta controlli mentali e allontana elementali ed esterni"));
        lvl1.add(new MagieMagoEStregone("Abiurazione", "Scudo", "Un disco invisibile fornisce +4 alla CA e blocca dardi incantati"));
        lvl1.add(new MagieMagoEStregone("Ammaliamento", "Charme su persone", "Rende una persona amichevole"));
        lvl1.add(new MagieMagoEStregone("Ammaliamento", "Ipnosi", "Affascina 2d4 DV di creature"));
        lvl1.add(new MagieMagoEStregone("Ammaliamento", "Sonno", "Fa cadere 4 DV di creature in un sonno magico"));
        lvl1.add(new MagieMagoEStregone("Divinazione", "Colpo accurato", "+20 al successivo tiro per colpire dell'incantatore"));
        lvl1.add(new MagieMagoEStregone("Divinazione", "Comprensione dei linguaggi", "L'incantatore comprende tutti i linguaggi scritti e parlati"));
        lvl1.add(new MagieMagoEStregone("Divinazione", "Identificare", "Determina le proprietà di un oggetto magico"));
        lvl1.add(new MagieMagoEStregone("Divinazione", "Individuazione dei non morti", "Rivela non morti nel raggio di 18 m"));
        lvl1.add(new MagieMagoEStregone("Divinazione", "Individuazione delle porte segrete", "Rivela porte nascoste entro 18 m"));
        lvl1.add(new MagieMagoEStregone("Evocazione", "Armatura magica", "Fornisce al soggetto un bonus di armatura +4"));
        lvl1.add(new MagieMagoEStregone("Evocazione", "Cavalcatura", "Evoca un cavallo da galoppo per 2 ore per livello"));
        lvl1.add(new MagieMagoEStregone("Evocazione", "Evoca mostri I", "Richiama una creatura extraplanare che combatte per l'incantatore"));
        lvl1.add(new MagieMagoEStregone("Evocazione", "Foschia occultante", "La nebbia avvolge l'incantatore"));
        lvl1.add(new MagieMagoEStregone("Evocazione", "Servitore inosservato", "Forza invisibile che esegue i comandi dell'incantatore"));
        lvl1.add(new MagieMagoEStregone("Evocazione", "Unto", "Rende scivoloso un quadrato con lato di 3m o un oggetto"));
        lvl1.add(new MagieMagoEStregone("Illusione", "Aura magica di Nystul", "Altera l'aura magica di un oggetto"));
        lvl1.add(new MagieMagoEStregone("Illusione", "Camuffare se stesso", "Modifica l'aspetto dell'incantatore"));
        lvl1.add(new MagieMagoEStregone("Illusione", "Immagine silenziosa", "Crea illusioni minori ideate dall'incantatore"));
        lvl1.add(new MagieMagoEStregone("Illusione", "Spruzzo colorato", "Rende privi di sensi, acceca e/o stordisce 1d6 creature deboli"));
        lvl1.add(new MagieMagoEStregone("Illusione", "Ventriloquio", "La voce risuona lontana per 1 minuto per livello"));
        lvl1.add(new MagieMagoEStregone("Invocazione", "Dardo incantato", "1d4+1 danni ; +1 dardo per ogni due livelli oltre il primo (max 5)"));
        lvl1.add(new MagieMagoEStregone("Invocazione", "Disco fluttuante di Tenser", "Crea un disco orizzontale del diametro di 90 cm che porta fino a 50 kg per livello"));
        lvl1.add(new MagieMagoEStregone("Invocazione", "Mani brucianti", "1d4 danni da fuoco per livello (max 5d4)"));
        lvl1.add(new MagieMagoEStregone("Invocazione", "Stretta folgorante", "A contatto infligge 1d6 danni da elettricità per livello (max 5d6)"));
        lvl1.add(new MagieMagoEStregone("Necromanzia", "Incuti paura", "Una creatura con 5 DV o meno diviene impaurita"));
        lvl1.add(new MagieMagoEStregone("Necromanzia", "Raggio di indebolimento", "Raggio che infligge 1d6 +1 danni alla For per ogni due livelli"));
        lvl1.add(new MagieMagoEStregone("Necromanzia", "Tocco gelido", "l tocco per livello infligge 1d6 danni e la possibilità di 1 danno alla For"));
        lvl1.add(new MagieMagoEStregone("Trasmutazione", "Animare corde", "Permette a una corda di muoversi a comando dell'incantatore"));
        lvl1.add(new MagieMagoEStregone("Trasmutazione", "Arma magica", "L'arma ottiene un bonus di +1"));
        lvl1.add(new MagieMagoEStregone("Trasmutazione", "Caduta morbida", "Oggetti o creature cadono lentamente"));
        lvl1.add(new MagieMagoEStregone("Trasmutazione", "Cancellare", "Scritte normali o magiche svaniscono."));
        lvl1.add(new MagieMagoEStregone("Trasmutazione", "Ingrandire persone", "Una creatura umanoide raddoppia le sue dimensioni"));
        lvl1.add(new MagieMagoEStregone("Trasmutazione", "Ridurre persone", "Una creatura umanoide dimezza le sue dimensioni"));
        lvl1.add(new MagieMagoEStregone("Trasmutazione", "Ritirata rapida", "La velocità dell'incantator e aumenta di 9 m"));
        lvl1.add(new MagieMagoEStregone("Trasmutazione", "Saltare", "Il soggetto ottiene un bonus alle prove di saltare"));

        lvl2.add(new MagieMagoEStregone("Abiurazione", "Occulta oggetto", "Maschera gli oggetti contro lo scrutamento"));
        lvl2.add(new MagieMagoEStregone("Abiurazione", "Protezione dalle frecce", "Il soggetto diventa immune a molti attacchi a distanza"));
        lvl2.add(new MagieMagoEStregone("Abiurazione", "Resistere all'energia", "Ignora 10 (o più) danni per ogni attacco da uno specifico tipo di energia"));
        lvl2.add(new MagieMagoEStregone("Abiurazione", "Serratura arcana", "Blocca magicamente una porta o uno scrigno"));
        lvl2.add(new MagieMagoEStregone("Ammaliamento", "Frastornare mostri", "Una creatura vivente con 6 DV o meno perde l'azione successiva"));
        lvl2.add(new MagieMagoEStregone("Ammaliamento", "Risata incontenibile di Tasha", "Il soggetto perde azioni per 1 round per livello"));
        lvl2.add(new MagieMagoEStregone("Ammaliamento", "Tocco di idiozia", "Il soggetto subisce 1d6 danni a Int, Sag e Car"));
        lvl2.add(new MagieMagoEStregone("Divinazione", "Individuazione dei pensieri", "Permette di ascoltare i pensieri superficiali"));
        lvl2.add(new MagieMagoEStregone("Divinazione", "Localizza oggetto", "Percepisce la direzione in cui si trova un oggetto (uno specifico o un tipo)"));
        lvl2.add(new MagieMagoEStregone("Divinazione", "Vedere invisibilità", "Rivela le creature o gli oggetti invisibili"));
        lvl2.add(new MagieMagoEStregone("Evocazione", "Evoca mostri II", "Richiama una creatura extraplanare che combatte per l'incantatore"));
        lvl2.add(new MagieMagoEStregone("Evocazione", "Evoca sciame", "Evoca uno sciame di pipistrelli, topi o ragni"));
        lvl2.add(new MagieMagoEStregone("Evocazione", "Freccia acida di Melf", "Un attacco di contatto a distanza ; 2d4 danni per 1 round + 1 round per ogni tre livelli"));
        lvl2.add(new MagieMagoEStregone("Evocazione", "Nube di nebbia", "Un banco di nebbia ostacola la visuale"));
        lvl2.add(new MagieMagoEStregone("Evocazione", "Polvere luccicante", "Acceca creature, delinea creature invisibili"));
        lvl2.add(new MagieMagoEStregone("Evocazione", "Ragnatela", "Riempie una propagazione del raggio di 6 m con fili di ragnatela appiccicosi"));
        lvl2.add(new MagieMagoEStregone("Illusione", "Bocca magica", "Parla una volta che viene attivata"));
        lvl2.add(new MagieMagoEStregone("Illusione", "Dissimulare", "Distorce divinazioni su di una creatura o un oggetto"));
        lvl2.add(new MagieMagoEStregone("Illusione", "Immagine minore", "Come immagine silenziosa, ma emette suoni"));
        lvl2.add(new MagieMagoEStregone("Illusione", "Immagine speculare", "Crea duplicati illusori dell'incantatore (1d4 immagini +1 per ogni tre livelli, max 8)"));
        lvl2.add(new MagieMagoEStregone("Illusione", "Invisibilità", "Il soggetto è invisibile per 1 minuto per livello o finché non attacca"));
        lvl2.add(new MagieMagoEStregone("Illusione", "Sfocatura", "Gli attacchi mancano il soggetto il 20% delle volte"));
        lvl2.add(new MagieMagoEStregone("Illusione", "Trama ipnotica", "Affascina (2d4+livello) DV di creature"));
        lvl2.add(new MagieMagoEStregone("Illusione", "Trappola di Leomune", "Fa apparire un oggetto protetto da una trappola"));
        lvl2.add(new MagieMagoEStregone("Invocazione", "Fiamma perenne", "Crea un torcia permanent e priva di calore"));
        lvl2.add(new MagieMagoEStregone("Invocazione", "Folata di vento", "Spazza via o butta a terra le creature più piccole"));
        lvl2.add(new MagieMagoEStregone("Invocazione", "Frantumare", "Le vibrazioni sonore danneggiano oggetti o creature cristalline"));
        lvl2.add(new MagieMagoEStregone("Invocazione", "Oscurità", "Penombra soprannaturale nel raggio di 6 m"));
        lvl2.add(new MagieMagoEStregone("Invocazione", "Raggio rovente", "Attacco di contatto a distanza che infligge 4d6 danni da fuoco, +1 raggio per ogni quattro livelli (max +3)"));
        lvl2.add(new MagieMagoEStregone("Invocazione", "Sfera infuocata", "Una palla di fuoco che rotola, infligge 2d6 danni e dura 1 round per livello"));
        lvl2.add(new MagieMagoEStregone("Necromanzia", "Cecità/Sordità", "Rende il soggetto cieco o sordo"));
        lvl2.add(new MagieMagoEStregone("Necromanzia", "Comandare non morti", "Una creatura non morta obbedisce agli ordini dell'incantatore"));
        lvl2.add(new MagieMagoEStregone("Necromanzia", "Mano spettrale", "Crea una mano spettrale insostaniale che sferra attacchi di contatto"));
        lvl2.add(new MagieMagoEStregone("Necromanzia", "Spaventare", "Creature con meno di 6 DV cadono in preda al panico"));
        lvl2.add(new MagieMagoEStregone("Necromanzia", "Tocco del ghoul", "Paralizza un soggetto, che eman a un fetore che rende infermi quanti gli sono vicini"));
        lvl2.add(new MagieMagoEStregone("Necromanzia", "Vita falsata", "Si ottengono 1d10 pf temporanei + 1 per livello (max +10)"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Alterare se stesso", "Permette di assumere la forma di una creatura simile"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Astuzia della volpe", "Il soggetto ottiene +4 all'Int per 1 minuto per livello"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Forza del toro", "Il soggetto ottiene +4 alla For per 1 minuto per livello"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Grazia del gatto", "Il soggetto ottiene +4 alla Des per 1 minuto per livello"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Levitazione", "Il soggetto si muove in alto e in basso per volontà dell'incantatore"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Movimenti del ragno", "Conferisce la capacità di camminare sulle pareti e sui soffitti"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Pirotecnica", "Trasforma i fuochi in luci accecanti o in fumo soffocante"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Resistenza dell'orso", "Il soggetto_ottiene +4 all a Cos per 1 minuto per livello"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Saggezza del gufo", "Il soggetto ottiene +4 alla Sag per 1 minuto per livello"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Scassinare", "Apre porte chiuse a chiave o sigillate magicamente"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Scurovisione", "Permette di vedere fino a 18 m nell'oscurità totale"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Splendore dell'aquila", "Il soggetto ottiene +4 al Car per 1 minuto per livello"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Trucco della corda", "Fino a otto creature possono nascondersi in uno spazio extradimensionale"));
        lvl2.add(new MagieMagoEStregone("Trasmutazione", "Vento sussurrante", "Invia un breve messaggio a 1,5 km per livello"));

        lvl3.add(new MagieMagoEStregone("Abiurazione", "Anti-individuazione", "Nasconde il soggetto a divinazione e scrutamento"));
        lvl3.add(new MagieMagoEStregone("Abiurazione", "Cerchio magico contro il bene/caos/legge/male", "Come gli incantesimi protezione, ma ha un raggio di 3 m e una durata di 10 minuti per livello"));
        lvl3.add(new MagieMagoEStregone("Abiurazione", "Dissolvi magie", "Cancella incantesimi ed effetti magici"));
        lvl3.add(new MagieMagoEStregone("Abiurazione", "Protezione dall'energia", "Assorbe 12 danni per livello da un tipo di energia"));
        lvl3.add(new MagieMagoEStregone("Abiurazione", "Rune esplosive", "Infliggono 6d6 danni quando vengono lette"));
        lvl3.add(new MagieMagoEStregone("Ammaliamento", "Blocca persone", "Paralizza un umanoide per 1 round per livello"));
        lvl3.add(new MagieMagoEStregone("Ammaliamento", "Eroismo", "Fornisce +2 ai tiri per colpire, ai tiri salvezza, alle prove di abilità"));
        lvl3.add(new MagieMagoEStregone("Ammaliamento", "Ira", "Fornisce +2 a For e Cos, +1 ai tiri salvezza sulla Volontà, -2 alla CA"));
        lvl3.add(new MagieMagoEStregone("Ammaliamento", "Sonno profondo", "Fa cadere nel sonno 10 DV di creature"));
        lvl3.add(new MagieMagoEStregone("Ammaliamento", "Suggestione", "Spinge il soggetto a intraprendere l'azione suggerita"));
        lvl3.add(new MagieMagoEStregone("Divinazione", "Chiaroudienza/Chiaroveggenza", "Eincantatore vede o sente a distanza per 1 minuto per livello"));
        lvl3.add(new MagieMagoEStregone("Divinazione", "Linguaggi", "Permette di parlare qualsiasi linguaggio"));
        lvl3.add(new MagieMagoEStregone("Divinazione", "Vista arcana", "L'incantatore riesce a vedere le aure magiche"));
        lvl3.add(new MagieMagoEStregone("Evocazione", "Destriero fantomatico", "Un cavallo magico appare per 1 ora per livello"));
        lvl3.add(new MagieMagoEStregone("Evocazione", "Nube maleodorante", "Vapori nauseanti per 1 round per livello"));
        lvl3.add(new MagieMagoEStregone("Evocazione", "Sigillo del serpente", "Crea simboli di testo che immobilizzano il lettore"));
        lvl3.add(new MagieMagoEStregone("Evocazione", "Tempesta di nevischio", "Ostacola la visione e il movimento"));
        lvl3.add(new MagieMagoEStregone("Illusione", "Distorsione", "Gli attacchi mancano il soggetto il 50% delle volte"));
        lvl3.add(new MagieMagoEStregone("Illusione", "Immagine maggiore", "Come immagine silenziosa ma emette suoni, odore e calore"));
        lvl3.add(new MagieMagoEStregone("Illusione", "Scritto illusorio'", "Solo il lettore designato è in grado di leggerlo"));
        lvl3.add(new MagieMagoEStregone("Illusione", "Sfera di invisibilità", "Rende invisibili coloro che si trovano nel raggio 3 m"));
        lvl3.add(new MagieMagoEStregone("Invocazione", "Capanna di Leomund", "Crea riparo per 10 creature"));
        lvl3.add(new MagieMagoEStregone("Invocazione", "Fulmine", "1d6 danni per livello da elettricità"));
        lvl3.add(new MagieMagoEStregone("Invocazione", "Luce diurna", "Luce intensa nel raggio di 18 m"));
        lvl3.add(new MagieMagoEStregone("Invocazione", "Muro di vento", "Respinge frecce, piccole creature ei gas"));
        lvl3.add(new MagieMagoEStregone("Invocazione", "Palla di fuoco", "1d6 danni per livello nel raggio d 4 m"));
        lvl3.add(new MagieMagoEStregone("Necromanzia", "Fermare non morti", "Immobilizza i non morti per 1 round per livello"));
        lvl3.add(new MagieMagoEStregone("Necromanzia", "Raggio di esaurimento", "Raggio che rende il soggetto esausto"));
        lvl3.add(new MagieMagoEStregone("Necromanzia", "Riposo inviolato", "Conserva un cadavere"));
        lvl3.add(new MagieMagoEStregone("Necromanzia", "Tocco del vampiro", "Attacco di contatto che infligge 1d6 danni per ogni due livelli; l'incantatore guadagna i danni come p"));
        lvl3.add(new MagieMagoEStregone("Trasmutazione", "Arma magica superiore", "+1 per ogni quattro livelli (max +5)"));
        lvl3.add(new MagieMagoEStregone("Trasmutazione", "Estremità affilata", "Raddoppia l'intervallo di minaccia di un'arma normale"));
        lvl3.add(new MagieMagoEStregone("Trasmutazione", "Forma gassosa", "Il soggetto diventa insostanziale e può volare lentamente"));
        lvl3.add(new MagieMagoEStregone("Trasmutazione", "Freccia infuocata", "Frecce che infliggono +1d6 danni da fuoco"));
        lvl3.add(new MagieMagoEStregone("Trasmutazione", "Intermittenza", "E incantatore scompare e riappare a caso per 1 round per livello"));
        lvl3.add(new MagieMagoEStregone("Trasmutazione", "Lentezza", "Un soggetto per livello compie solo un'azione per round, ha -1 alla CA e ai tiri per colpire"));
        lvl3.add(new MagieMagoEStregone("Trasmutazione", "Pagina segreta", "Cambia l'aspetto di una pagina per nasconderne il reale contenuto"));
        lvl3.add(new MagieMagoEStregone("Trasmutazione", "Respirare sott'acqua", "Il soggetto può respirare sott'acqua"));
        lvl3.add(new MagieMagoEStregone("Trasmutazione", "Restringere oggetto", "L'oggetto si riduce a un sedicesimo della sua taglia"));
        lvl3.add(new MagieMagoEStregone("Trasmutazione", "Velocità", "Una creatura per livello si muove più veloce, +1 ai tiri per colpire, alla CA e ai tiri salvezza sui Riflessi"));
        lvl3.add(new MagieMagoEStregone("Trasmutazione", "Volare", "Il soggetto vola con una velocità di 18 m"));


        lvl4.add(new MagieMagoEStregone("Abiurazione", "Ancora dimensionale", "Impedisce il viaggio extra dimensionale"));
        lvl4.add(new MagieMagoEStregone("Abiurazione", "Globo di invulnerabilità inferiore", "Impedisce gli effetti di incantesimi dal 1° al 3° livello"));
        lvl4.add(new MagieMagoEStregone("Abiurazione", "Pelle di pietra", "Ignora 10 danni per ogni attacco"));
        lvl4.add(new MagieMagoEStregone("Abiurazione", "Rimuovi maledizione", "Libera un oggetto o una persona da una maledizione"));
        lvl4.add(new MagieMagoEStregone("Abiurazione", "Trappola di fuoco'", "Gli oggetti che vengono aperti infliggono 1d4 danni + 1 danno per livello"));
        lvl4.add(new MagieMagoEStregone("Ammaliamento", "Charme sui mostri", "Convince un mostro che l'incantatore è un suo alleato"));
        lvl4.add(new MagieMagoEStregone("Ammaliamento", "Confusione", "Rende bizzarro il comportamento del soggetto per 1 round per livello"));
        lvl4.add(new MagieMagoEStregone("Ammaliamento", "Costrizione inferiore", "Comanda un soggetto con 7 DV o meno"));
        lvl4.add(new MagieMagoEStregone("Ammaliamento", "Disperazione opprimente", "I soggetti subiscono -2 ai tiri per colpire, per i danni, ai tiri salvezza e alle prove"));
        lvl4.add(new MagieMagoEStregone("Divinazione", "Individuazione dello scrutamento", "Avverte l' inntcantatore di chi lo spia magicamente"));
        lvl4.add(new MagieMagoEStregone("Divinazione", "Localizza creatura", "Indica la direzione di una creatura familiare"));
        lvl4.add(new MagieMagoEStregone("Divinazione", "Occhio arcano", "Un occhio fluttuante invisibile si muove a 9 m per round"));
        lvl4.add(new MagieMagoEStregone("Divinazione", "Scrutare'", "Spia soggetti a distanza"));
        lvl4.add(new MagieMagoEStregone("Evocazione", "Creazione minore", "Crea un oggetto di tessuto o di legno"));
        lvl4.add(new MagieMagoEStregone("Evocazione", "Evoca mostri IV", "Richiama una creatura extraplanare che combatte per l'incantatore"));
        lvl4.add(new MagieMagoEStregone("Evocazione", "Nebbia solida", "Blocca la visuale e rallenta il movimento"));
        lvl4.add(new MagieMagoEStregone("Evocazione", "Porta dimensionale", "Teletrasporta l'incantatore per una breve distanza"));
        lvl4.add(new MagieMagoEStregone("Evocazione", "Riparosicuro di Leomund", "Crea un solido rifugio"));
        lvl4.add(new MagieMagoEStregone("Evocazione", "Tentacoli neri di Evard", "Tentacoli lottano con quanti si trovano in una propagazione di 4,5 m"));
        lvl4.add(new MagieMagoEStregone("Illusione", "Allucinazione mortale", "Un'illusione spaventosa, uccide il soggetto o infligge 3d6 danni"));
        lvl4.add(new MagieMagoEStregone("Illusione", "Invisibilità superiore", "Come invisibilità ma il soggetto può attaccare e rimanere invisibile"));
        lvl4.add(new MagieMagoEStregone("Illusione", "Muro illusorio", "Un muro, un pavimento o un soffitto sembrano reali, ma vi si può passare attraverso"));
        lvl4.add(new MagieMagoEStregone("Illusione", "Ombra di una evocazione", "Simula evocazioni inferiori al 4' livello, ma reali solo al 20%"));
        lvl4.add(new MagieMagoEStregone("Illusione", "Terreno illusorio", "Fa apparire un tipo di terreno come un altro tipo (campi in foreste ecc .)"));
        lvl4.add(new MagieMagoEStregone("Illusione", "Trama iridescente", "Le luci affascinano 24 DV di creature"));
        lvl4.add(new MagieMagoEStregone("Invocazione", "Grido", "Rende sordi i soggetti all'interno del cono e infligge 5d6 danni sonori"));
        lvl4.add(new MagieMagoEStregone("Invocazione", "Muro di fuoco", "Infligge 2d4 danni da fuoco fino a 3 m e 1d4 fino a 6 m . Passare attraverso il muro infligge 2d6 danni +1 danno per livello"));
        lvl4.add(new MagieMagoEStregone("Invocazione", "Muro di ghiaccio", "Piano di ghiaccio crea un muro con 15 pf + 1 pf per livello, o semisfera può intrappolare delle creature al suo interno"));
        lvl4.add(new MagieMagoEStregone("Invocazione", "Scudo di fuoco", "Le creature che attaccano l'incantatore subiscono danni da fuoco; l'incantatore è protetto dal calore o dal freddo"));
        lvl4.add(new MagieMagoEStregone("Invocazione", "Sfera elastica di Otiluke", "Un globo di forza protegge ma intrappola un soggetto"));
        lvl4.add(new MagieMagoEStregone("Invocazione", "Tempesta di ghiaccio", "La grandine infligge 5d6 danni in un cilindro dell'ampiezza di 12 m"));
        lvl4.add(new MagieMagoEStregone("Necromanzia", "Animare morti'", "Crea scheletri e zombi non morti"));
        lvl4.add(new MagieMagoEStregone("Necromanzia", "Contagio", "Infetta il soggetto con la malattia scelta"));
        lvl4.add(new MagieMagoEStregone("Necromanzia", "Debilitazione", "Il soggetto ottiene 1d4 livelli negativi"));
        lvl4.add(new MagieMagoEStregone("Necromanzia", "Paura", "I soggetti all'interno del cono fuggono per 1round per livello"));
        lvl4.add(new MagieMagoEStregone("Necromanzia", "Scagliare maledizione", "-6 a un punteggio di caratteristica, -4 ai tiri per colpire, ai tiri salvezza e alle prove; o probabilità del 50% di perdere ogni azione"));
        lvl4.add(new MagieMagoEStregone("Trasmutazione", "Ingrandire persone di massa", "Ingrandisce diverse creature"));
        lvl4.add(new MagieMagoEStregone("Trasmutazione", "Metamorfosi", "Conferisce a un soggetto consenziente una nuova forma"));
        lvl4.add(new MagieMagoEStregone("Trasmutazione", "Potenziatore mnemonico di Rary'", "Prepara incantesimi extra o ne recupera uno appena lanciato. Solo per i maghi"));
        lvl4.add(new MagieMagoEStregone("Trasmutazione", "Ridurre persone di massa", "Riduce diverse creature"));

        lvl5.add(new MagieMagoEStregone("Abiurazione", "Congedo", "Costringe una creatura a tornare al suo piano natio"));
        lvl5.add(new MagieMagoEStregone("Abiurazione", "Santuario privato di Mordenkainen", "Impedisce a chiunque di vedere o scrutare in un'area per 24 ore"));
        lvl5.add(new MagieMagoEStregone("Abiurazione", "Spezzare incantamento", "Libera i soggetti da ammaliamenti, alterazioni, maledizioni e pietrificazioni"));
        lvl5.add(new MagieMagoEStregone("Ammaliamento", "Blocca mostri", "Come blocca persone, ma su qualsiasi creatura"));
        lvl5.add(new MagieMagoEStregone("Ammaliamento", "Dominare persone", "Controlla un umanoidibtelepaticamente"));
        lvl5.add(new MagieMagoEStregone("Ammaliamento", "Nebbia mentale", "I soggetti nella nebbia subiscono -10 a Sag e alle prove di Volontà"));
        lvl5.add(new MagieMagoEStregone("Ammaliamento", "Regressione mentale", "Int e Car del soggetto scendono a 1"));
        lvl5.add(new MagieMagoEStregone("Ammaliamento", "Simbolo di sonno", "Runa che fa cadere le creature vicine in un sonno catatonico"));
        lvl5.add(new MagieMagoEStregone("Divinazione", "Contattare altri piani", "Pone una domanda a un'entità extraplanare"));
        lvl5.add(new MagieMagoEStregone("Divinazione", "Legame telepatico di Rary", "Il collegamento permette agli alleati di comunicare"));
        lvl5.add(new MagieMagoEStregone("Divinazione", "Occhi indagatori", "1d4 +t per livello occhi fluttuanti che esplorano per l'incantator"));
        lvl5.add(new MagieMagoEStregone("Evocazione", "Creazione maggiore", "Come creazione minore, ma anche di pietra e di metallo"));
        lvl5.add(new MagieMagoEStregone("Evocazione", "Evoca mostri V", "Richiama una creatura extraplanare che combatte per l'incantatore"));
        lvl5.add(new MagieMagoEStregone("Evocazione", "Legame planare inferiore", "Intrappola una creatura extraplanare con 6 DV o meno finché non esegue un compito"));
        lvl5.add(new MagieMagoEStregone("Evocazione", "Muro di pietra", "Crea un muro di pietra che può essere plasmato"));
        lvl5.add(new MagieMagoEStregone("Evocazione", "Nube mortale", "Uccide creature con 3 DV o meno; 4-6 DV tiro salvezza o muoiono, più di 6 DV subiscono danni alla Cos"));
        lvl5.add(new MagieMagoEStregone("Evocazione", "Scrigno segreto di LeomundF", "Nasconde un o scrigno prezioso sul Piano Etereo ; l'incantatore può recuperarlo a suo piacimento"));
        lvl5.add(new MagieMagoEStregone("Evocazione", "Segugio fedele di Mordenkainen", "Un cane fantomatico che può fare la guardia o attaccare"));
        lvl5.add(new MagieMagoEStregone("Evocazione", "Teletrasporto", "Trasporta istantaneamente 1'incantatore a una distanza di t 50 km per livell"));
        lvl5.add(new MagieMagoEStregone("Illusione", "Immagine persistente", "Come immagine maggiore, ma non è necessaria la concentrazione"));
        lvl5.add(new MagieMagoEStregone("Illusione", "Incubo", "Invia una visione che provoca 1d10 danni e affaticamento"));
        lvl5.add(new MagieMagoEStregone("Illusione", "Miraggio arcano", "Come terreno illusorio, con in più le strutture"));
        lvl5.add(new MagieMagoEStregone("Illusione", "Ombra di una invocazione", "Simula invocazion inferiori al 5° livello, ma reali solo al 20%"));
        lvl5.add(new MagieMagoEStregone("Illusione", "Sembrare", "Cambia l'aspetto di una persona per ogni due livelliSogno: Invia un messaggio a qualcuno che sta dormendo"));
        lvl5.add(new MagieMagoEStregone("Illusione", "Visione falsa", "Inganna lo scrutamento con un'illusion"));
        lvl5.add(new MagieMagoEStregone("Invocazione", "Cono di freddo", "1d6 danni da freddo per livello"));
        lvl5.add(new MagieMagoEStregone("Invocazione", "Inviare", "Riferisce un breve messaggio ovunque istantaneamente"));
        lvl5.add(new MagieMagoEStregone("Invocazione", "Mano interposta di Bigby", "Una mano che fornisce copertura contro un avversario"));
        lvl5.add(new MagieMagoEStregone("Invocazione", "Muro di forza", "Un muro immune ai danni"));
        lvl5.add(new MagieMagoEStregone("Necromanzia", "Giara magica'", "Consente la possessione di un'altra creatura"));
        lvl5.add(new MagieMagoEStregone("Necromanzia", "Inaridire", "Fa appassire un vegetale o infligge 1d6 danni per livello a una creatura vegetale"));
        lvl5.add(new MagieMagoEStregone("Necromanzia", "Onde di affaticamento", "Parecchi bersagli diventano affaticati"));
        lvl5.add(new MagieMagoEStregone("Necromanzia", "Simbolo di dolore", "Runa che devasta le creature vicine con dolori indicibili"));
        lvl5.add(new MagieMagoEStregone("Trasmutazione", "Crescita animale", "Un animale per ogni due livelli raddoppia le dimensioni"));
        lvl5.add(new MagieMagoEStregone("Trasmutazione", "Fabbricare", "Trasforma materie prime in oggetti rifiniti"));
        lvl5.add(new MagieMagoEStregone("Trasmutazione", "Metamorfosi funesta", "Trasforma il soggetto in un animale innocuo"));
        lvl5.add(new MagieMagoEStregone("Trasmutazione", "Passapareti", "Crea un passaggio attraverso pareti di legno e pietra"));
        lvl5.add(new MagieMagoEStregone("Trasmutazione", "Scolpire pietra", "Plasma la pietra in qualsiasi forma"));
        lvl5.add(new MagieMagoEStregone("Trasmutazione", "Telecinesi", "Sposta un oggetto, attacca una creatura o lancia un oggetto o una creatura"));
        lvl5.add(new MagieMagoEStregone("Trasmutazione", "Trasmutare fango in roccia", "Trasforma due cubi con spigolo di 3 m per livello"));
        lvl5.add(new MagieMagoEStregone("Trasmutazione", "Trasmutare roccia in fango", "Trasforma due cubi con spigolo di 3 tn per livello"));
        lvl5.add(new MagieMagoEStregone("Trasmutazione", "Volo giornaliero", "L'incantatore vola con una velocità di 12 m e può andare veloce nelle lunghe distanze"));
        lvl5.add(new MagieMagoEStregone("Universale", "Permanenza'", "Rende alcuni incantesimi permanenti"));

        lvl6.add(new MagieMagoEStregone("Abiurazione", "Campo anti-magia", "Nega la magia nel raggio di 3 m"));
        lvl6.add(new MagieMagoEStregone("Abiurazione", "Dissolvi magie superiore", "Come dissolvi magie ma fino a +20 alla prova"));
        lvl6.add(new MagieMagoEStregone("Abiurazione", "Globo di invulnerabilità", "Come globo di invulnerabilità inferiore, più effetti di incantesimi di 4° livello"));
        lvl6.add(new MagieMagoEStregone("Abiurazione", "Repulsione", "Le creature non possono avvicinarsi all'incantatore"));
        lvl6.add(new MagieMagoEStregone("Abiurazione", "Vigilanza e interdizione", "Una serie di difese magiche per proteggere un'area"));
        lvl6.add(new MagieMagoEStregone("Ammaliamento", "Costrizione/Cerca", "Come costrizione inferiore ma influenza qualsiasi creatura"));
        lvl6.add(new MagieMagoEStregone("Ammaliamento", "Eroismo superiore", "Fornisce un bonus di +4 ai tiri per colpire, ai tiri salvezza, alle prove di abilità ; immunità alla paura ; pf temporanei"));
        lvl6.add(new MagieMagoEStregone("Ammaliamento", "Simbolo di persuasione", "Runa che rende le creature vicine soggette a charme"));
        lvl6.add(new MagieMagoEStregone("Ammaliamento", "Suggestione di massa", "Come suggestione, più un soggetto per livello"));
        lvl6.add(new MagieMagoEStregone("Divinazione", "Analizzare dweomer'", "Rivela gli aspetti magici di un soggetto"));
        lvl6.add(new MagieMagoEStregone("Divinazione", "Conoscenza delle leggende", "L'incantatore apprende storie su una persona, un luogo o un oggetto"));
        lvl6.add(new MagieMagoEStregone("Divinazione", "Visione del vero'", "Permette di vedere tutte le cose per quello che sono veramente"));
        lvl6.add(new MagieMagoEStregone("Evocazione", "Evoca mostri VI", "Richiama una creatura extraplanare che combatte per l'incantatore"));
        lvl6.add(new MagieMagoEStregone("Evocazione", "Legame planare", "Come legame planare inferiore ma fino a 12 DV"));
        lvl6.add(new MagieMagoEStregone("Evocazione", "Muro di ferro", "30 pf per ogni quattro livelli ; può cadere addosso ai nemici"));
        lvl6.add(new MagieMagoEStregone("Evocazione", "Nebbia acida", "Nebbia che infligge danni da acido"));
        lvl6.add(new MagieMagoEStregone("Illusione", "Camminare nelle ombre", "Permette di entrare nell'ombra per viaggiare rapidamente"));
        lvl6.add(new MagieMagoEStregone("Illusione", "Fuorviare", "Rende l'incantatore invisibile e crea un suo sosia illusorio"));
        lvl6.add(new MagieMagoEStregone("Illusione", "Immagine permanente'", "Include vista, suono e odore"));
        lvl6.add(new MagieMagoEStregone("Illusione", "Immagine programmata'", "Come immagine maggiore, ma attivata da un evento"));
        lvl6.add(new MagieMagoEStregone("Illusione", "Velo", "Cambia l'aspetto di un gruppo di creature"));
        lvl6.add(new MagieMagoEStregone("Invocazione", "Catena di fulmini", "1d6 danni per livello; 1 fulmine secondario per livello di cui ognuno infligge danni dimezzati"));
        lvl6.add(new MagieMagoEStregone("Invocazione", "Contingenza", "Fa scattare le condizioni per l'attivazione di un altro incantesimo"));
        lvl6.add(new MagieMagoEStregone("Invocazione", "Mano possente di Bigby", "Una mano che spinge via le creature"));
        lvl6.add(new MagieMagoEStregone("Invocazione", "Sfera congelante di Otiluke", "Congela l'acqua o infligge danni da freddo"));
        lvl6.add(new MagieMagoEStregone("Necromanzia", "Cerchio di morte", "Uccide 1d4 DV di creature per livello"));
        lvl6.add(new MagieMagoEStregone("Necromanzia", "Creare non morti", "Per creare ghoul, ghast, mummie o mohrg"));
        lvl6.add(new MagieMagoEStregone("Necromanzia", "Non morto a morto", "Distrugge 1d4 DV per livello di non morti (max 20d4)"));
        lvl6.add(new MagieMagoEStregone("Necromanzia", "Sguardo penetrante", "Il bersaglio diventa in preda al panico, infermo e in stato comatoso"));
        lvl6.add(new MagieMagoEStregone("Necromanzia", "Simbolo di paura", "Rama che fa cadere le creatur e vicine in preda al panico"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Astuzia della volpe di massa", "Come astuzia della volpe, ma influenza un soggetto per livello"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Carne in pietra", "Trasforma una creatura in una statua"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Controllare acqua", "Solleva o abbassa masse d'acqua"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Disintegrazione", "Fa svanire una creatura o un oggetto"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Elucubrazione di Mordenkainen", "Fa ricordare incantesimi di 5° livello o inferiori . Solo per i maghi"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Forza del toro di massa", "Come forza del toro, ma influenza un soggetto per livello"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Grazia del gatto di massa", "Come grazia del gatto, ma influenza un soggetto per livello"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Muovere il terreno", "Scava trincee e fa crescere colline"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Pietra in carne", "Ristabilisce una creatura pietrificata"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Resistenza dell'orso di massa", "Come resistenza dell'orso, ma influenza un soggetto per livello"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Saggezza del gufo di massa", "Come saggezza del gufo, ma influenza un soggetto per livello"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Splendore dell'aquila di massa", "Come splendore dell'aquila, ma influenza un soggetto per livello"));
        lvl6.add(new MagieMagoEStregone("Trasmutazione", "Trasformazione diTenser", "Lincantatore ottiene bonus di combattimento"));

        lvl7.add(new MagieMagoEStregone("Abiurazione", "Celare", "Il soggetto è invisibile alla vista e allo scrutamento ; fa cadere la creatura in uno stat o comatoso"));
        lvl7.add(new MagieMagoEStregone("Abiurazione", "Esilio", "Bandisce 2 DV per livello di creature extraplanari"));
        lvl7.add(new MagieMagoEStregone("Abiurazione", "Riflettere incantesimo", "Riflette 1d4+6 livelli di incantesimo contro chi ha lanciato l'incantesimo"));
        lvl7.add(new MagieMagoEStregone("Ammaliamento", "Blocca persone dimassa", "Come blocca persone, ma tutti entro 9 m"));
        lvl7.add(new MagieMagoEStregone("Ammaliamento", "Demenza", "Il soggetto è in preda a una confusione continua"));
        lvl7.add(new MagieMagoEStregone("Ammaliamento", "Parola del potere, accecare", "Acceca una creatura con 200 pf o meno"));
        lvl7.add(new MagieMagoEStregone("Ammaliamento", "Simbolo di stordimento", "Runa che stordisce le creature vicine"));
        lvl7.add(new MagieMagoEStregone("Divinazione", "Scrutare superiore", "Come scrutare, ma più velocemente e più a lungo"));
        lvl7.add(new MagieMagoEStregone("Divinazione", "Visione", "Come conoscenza delle leggende, ma più veloce e faticosa"));
        lvl7.add(new MagieMagoEStregone("Divinazione", "Vista arcana superiore", "Come vista arcana, ma rivela anche gli effetti magici sulle creature e sugli oggetti"));
        lvl7.add(new MagieMagoEStregone("Evocazione", "Evoca mostri VII", "Richiama una creatura extraplanare che combatte per l'incantatore"));
        lvl7.add(new MagieMagoEStregone("Evocazione", "Evocazioni istantanee di Drawmij", "Un oggetto preparato appare nella mano dell'incantatore"));
        lvl7.add(new MagieMagoEStregone("Evocazione", "Porta in fase", "Crea un passaggio invisibile attraverso il legno o la pietra"));
        lvl7.add(new MagieMagoEStregone("Evocazione", "Reggia meravigliosa di Mordenkainen'", "Una porta conduce a una reggia extradimensionale"));
        lvl7.add(new MagieMagoEStregone("Evocazione", "Spostamento planare'", "Fino a ottosoggetti viaggiano su un altro piano"));
        lvl7.add(new MagieMagoEStregone("Evocazione", "Teletrasporto degli oggetti", "Come teletrasporto, ma ha effetto su un oggetto toccato"));
        lvl7.add(new MagieMagoEStregone("Evocazione", "Teletrasporto superiore", "Come teletrasporto, ma senza limiti di raggio di azion"));
        lvl7.add(new MagieMagoEStregone("Illusione", "Immagine proiettata", "Un sosia illusorio in grado di parlare e lanciare incantesimi"));
        lvl7.add(new MagieMagoEStregone("Illusione", "Invisibilità di massa", "Come invisibilità, ma ha effetto su tutti i presemi nel raggio di azione"));
        lvl7.add(new MagieMagoEStregone("Illusione", "Ombra di una evocazione superiore", "Come ombra di una evocazione, ma fino al 6° livello e reali al 60%"));
        lvl7.add(new MagieMagoEStregone("Illusione", "Simulacro", "Crea un sosia parzialmente reale di una creatura"));
        lvl7.add(new MagieMagoEStregone("Invocazione", "Gabbia di forza to", "Un cubo o una gabbia di forza che imprigiona tutti al suo interno"));
        lvl7.add(new MagieMagoEStregone("Invocazione", "Mano stringente di Bigby", "Una mano che fornisce copertura, spinge o lotta"));
        lvl7.add(new MagieMagoEStregone("Invocazione", "Palla di fuoco ritardata", "1d6 danni da fuoco per livello ; è possibile ritardare l'esplosione per 5 round"));
        lvl7.add(new MagieMagoEStregone("Invocazione", "Spada di Mordenkainen'", "Una lama magica fluttuante che colpisce gli avversari"));
        lvl7.add(new MagieMagoEStregone("Invocazione", "Spruzzo prismatico", "Un raggio che colpisce i soggetti con una varietà di effetti"));
        lvl7.add(new MagieMagoEStregone("Necromanzia", "Controllare non morti", "I non morti non attaccano l'incantatore finché rimangono sotto il suo comando"));
        lvl7.add(new MagieMagoEStregone("Necromanzia", "Dito della morte", "Uccide un soggetto"));
        lvl7.add(new MagieMagoEStregone("Necromanzia", "Onde di esaurimento", "Parecchi bersagli diventano esausti"));
        lvl7.add(new MagieMagoEStregone("Necromanzia", "Simbolo di debolezza", "Runa che indebolisce le creature vicine"));
        lvl7.add(new MagieMagoEStregone("Trasmutazione", "Controllare tempo atmosferico", "Cambia il tempo atmosferico in un'area"));
        lvl7.add(new MagieMagoEStregone("Trasmutazione", "Inversione della gravità", "Gli oggetti e le creature cadono verso l'alto"));
        lvl7.add(new MagieMagoEStregone("Trasmutazione", "Statua", "Un soggetto può trasformarsi in statua a suo piacimento"));
        lvl7.add(new MagieMagoEStregone("Trasmutazione", "Transizione eterea", ".:incantatore diventa etereo per 1 round per livello"));
        lvl7.add(new MagieMagoEStregone("Universale", "Desiderio limitato", "Altera la realtà, entro i termini consentiti dall'incantesimo"));

        lvl8.add(new MagieMagoEStregone("Abiurazione", "Muro prismatico", "I colori del muro hanno una serie di effetti"));
        lvl8.add(new MagieMagoEStregone("Abiurazione", "Protezione dagli incantesimi", "Conferisce un bonus di resistenza +8"));
        lvl8.add(new MagieMagoEStregone("Abiurazione", "Serratura dimensionale", "Teletrasporto e viaggi interplanari bloccati per 1 giorno per livello"));
        lvl8.add(new MagieMagoEStregone("Abiurazione", "Vuoto mentale", "Il soggetto è immune alle magie mentali/emozionali e allo scrutamento"));
        lvl8.add(new MagieMagoEStregone("Ammaliamento", "Antipatia", "!:oggetto o la locazione influenzata respingono certe creature"));
        lvl8.add(new MagieMagoEStregone("Ammaliamento", "Charme sui mostri di massa", "Come charme sui mostri, ma ha effetto sui presenti entro 9 m"));
        lvl8.add(new MagieMagoEStregone("Ammaliamento", "Danza irresistibile di Otto", "Costringe il soggetto a danzare"));
        lvl8.add(new MagieMagoEStregone("Ammaliamento", "Esigere", "Come inviare, ma è anche possibile inviare una suggestione"));
        lvl8.add(new MagieMagoEStregone("Ammaliamento", "Legame", "Una serie di tecniche per imprigionare una creatura"));
        lvl8.add(new MagieMagoEStregone("Ammaliamento", "Parola del potere, stordire", "Stordisce una creatura con 150 pf o meno"));
        lvl8.add(new MagieMagoEStregone("Ammaliamento", "Simbolo di demenza", "Runa che rende dementi le creature vicine"));
        lvl8.add(new MagieMagoEStregone("Ammaliamento", "Simpatia", "L'oggetto o la locazione influenzata attraggono certe creature"));
        lvl8.add(new MagieMagoEStregone("Divinazione", "Momento di prescienza", "I:incantatore ottiene un bonus cognitivo su un singolo tiro per colpire, prova o tiro salvezza"));
        lvl8.add(new MagieMagoEStregone("Divinazione", "Occhi indagatori superiore", "Come occhi indagatori, ma gli occhi hanno visione del vero"));
        lvl8.add(new MagieMagoEStregone("Divinazione", "Rivela locazioni", "Locazione esatta di una creatura o di un oggetto"));
        lvl8.add(new MagieMagoEStregone("Evocazione", "Evoca mostri VIII", "Richiama una creatura extraplanare che combatte per l'incantatore"));
        lvl8.add(new MagieMagoEStregone("Evocazione", "Intrappolare l'anima", "Imprigiona il soggetto all'interno di una gemma"));
        lvl8.add(new MagieMagoEStregone("Evocazione", "Labirinto", "Intrappola il soggetto in un labirinto extradimensionale"));
        lvl8.add(new MagieMagoEStregone("Evocazione", "Legame planare superiore", "Come legame planare inferiore ma fino a 18 DV"));
        lvl8.add(new MagieMagoEStregone("Evocazione", "Nube incendiaria", "Una nuvola che infligge 4d6 danni da fuoco per round"));
        lvl8.add(new MagieMagoEStregone("Illusione", "Ombra di una invocazione superiore", "Come ombra di una invocazione, ma fino al 7° livello e reali al 60%"));
        lvl8.add(new MagieMagoEStregone("Illusione", "Schermo", "Un'illusione che nasconde un'area da visione e scartamento"));
        lvl8.add(new MagieMagoEStregone("Illusione", "Trama scintillante", "Colori contorti che stordiscono, rendono confusi o privi di sensi"));
        lvl8.add(new MagieMagoEStregone("Invocazione", "Esplosione solare", "Acceca tutti nel raggio di 24 m, infligge 6d6 danni"));
        lvl8.add(new MagieMagoEStregone("Invocazione", "Grido superiore", "Un urlo devastante infligge 10d6 danni sonori; stordisce le creature , danneggia gli oggetti"));
        lvl8.add(new MagieMagoEStregone("Invocazione", "Pugno serrato di Bigby", "Una mano Grande fornisce copertura, spinge e attacca i nemici dell'incantatore"));
        lvl8.add(new MagieMagoEStregone("Invocazione", "Raggio polare", "Attacco di contatto a distanza che infligge 1d6 danni da freddo per livello"));
        lvl8.add(new MagieMagoEStregone("Invocazione", "Sfera telecinetica di Otiluke", "Come sfera elastica di Oliluke, ma l'incantatore è in grado di spostarla telecinericamente"));
        lvl8.add(new MagieMagoEStregone("Necromanzia", "Clone", "Un duplicato che si risveglia quando l'originale muore"));
        lvl8.add(new MagieMagoEStregone("Necromanzia", "Creare non morti superiori", "Per creare ombre , wraith, spettri o divoratori."));
        lvl8.add(new MagieMagoEStregone("Necromanzia", "Orrido avvizzimento", "Infligge 1d6 danni per livello nel raggio di 9 M"));
        lvl8.add(new MagieMagoEStregone("Necromanzia", "Simbolo di morte", "Runa che uccide le creature vicine"));
        lvl8.add(new MagieMagoEStregone("Trasmutazione", "Corpo di ferro", "il corpo dell'incantatore diventa di ferro vivente"));
        lvl8.add(new MagieMagoEStregone("Trasmutazione", "Metamorfosi di un oggetto", "Trasforma un soggetto in qualcos'altro"));
        lvl8.add(new MagieMagoEStregone("Trasmutazione", "Stasi temporale", "Mette il soggetto in animazione sospesa"));


        lvl9.add(new MagieMagoEStregone("Abiurazione", "Disgiunzione di Mordenkainen", "magia e disincanta oggetti magici"));
        lvl9.add(new MagieMagoEStregone("Abiurazione", "Imprigionare", "Seppellisce il soggetto sotto terra"));
        lvl9.add(new MagieMagoEStregone("Abiurazione", "Libertà", "Libera le creature sotto gli effetti di imprigionare"));
        lvl9.add(new MagieMagoEStregone("Abiurazione", "Sfera prismatica", "Come muro prismatico ma circonda da ogni lato"));
        lvl9.add(new MagieMagoEStregone("Ammaliamento", "Blocca mostri di massa", "Come blocca mostri, ma tutti i presenti entro 9 m"));
        lvl9.add(new MagieMagoEStregone("Ammaliamento", "Dominare mostri", "Come dominare persone, ma su qualsiasi creatura"));
        lvl9.add(new MagieMagoEStregone("Ammaliamento", "Parola del potere, uccidere", "Uccide una creatura con 100 pf o men"));
        lvl9.add(new MagieMagoEStregone("Evocazione", "Cerchio di teletrasporto", "Un cerchio teletrasporta qualsiasi creatura che vi entri in un posto prestabilito"));
        lvl9.add(new MagieMagoEStregone("Evocazione", "Evoca mostri IX", "Richiama una creatura extraplanare che combatte per l'incantatore."));
        lvl9.add(new MagieMagoEStregone("Evocazione", "Portale'", "Collega due piani per viaggiare o per evocare creatur"));
        lvl9.add(new MagieMagoEStregone("Evocazione", "Rifugio", "Altera un oggetto per trasportare il suo possessore fino all'incantatore"));
        lvl9.add(new MagieMagoEStregone("Illusione", "Fatale", "Come allucinazione mortale, ma ha effetto su tutti i presenti entro 9 m"));
        lvl9.add(new MagieMagoEStregone("Illusione", "Ombre", "Come ombra di una evocazione, ma fino all'8° livello e reali all'80%"));
        lvl9.add(new MagieMagoEStregone("Invocazione", "Mano stritolatrice di Bigby", "Una mano Grande che fornisce copertura, spinge o schiaccia i nemici dell'incantatore"));
        lvl9.add(new MagieMagoEStregone("Invocazione", "Sciame di meteore", "Quattro sfere esplosive di cui ognuna infligge 6d6 danni da fuoco"));
        lvl9.add(new MagieMagoEStregone("Necromanzia", "Lamento della banshee", "Uccide una creatura per livello"));
        lvl9.add(new MagieMagoEStregone("Necromanzia", "Legare anima", "Intrappola un'anima appena morta per impedirne la resurrezione"));
        lvl9.add(new MagieMagoEStregone("Necromanzia", "Proiezione astrale", "Proietta l'incantatore e i suoi compagni sul Piano Astrale"));
        lvl9.add(new MagieMagoEStregone("Necromanzia", "Risucchio di energia", "Il soggetto ottiene 2d4 livelli negativi"));
        lvl9.add(new MagieMagoEStregone("Trasmutazione", "Fermare il tempo", "L'incantatore può agire liberamente per 1d4+1 round"));
        lvl9.add(new MagieMagoEStregone("Trasmutazione", "Forma eterea", "Per viaggiare sul Piano Etereo con i compagni"));
        lvl9.add(new MagieMagoEStregone("Trasmutazione", "Trasformazione", "Eincantatore si trasforma in qualsiasi creatura e può cambiare forma una volta per round"));
        lvl9.add(new MagieMagoEStregone("Universale", "Desiderio", "Come desiderio limitato, ma con meno limiti"));
    }
}
